In [19]:
import torch
import numpy as np

In [3]:
def describe(x):
  print(f"Type: {type(x)}")
  print(f"Shape: {x.shape}")
  print(f"Values: {x}")

In [4]:
x = torch.Tensor(2, 3)
describe(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[0.0000e+00, 3.6893e+19, 0.0000e+00],
        [3.6893e+19, 3.5032e-44, 0.0000e+00]])


In [7]:
describe(torch.rand(2, 10))
describe(torch.randn(2, 10))

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 10])
Values: tensor([[0.5706, 0.0451, 0.2723, 0.0277, 0.0746, 0.3107, 0.2363, 0.5000, 0.5788,
         0.3575],
        [0.5772, 0.5741, 0.0676, 0.4101, 0.6189, 0.8512, 0.7212, 0.5977, 0.9278,
         0.6591]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 10])
Values: tensor([[-0.6553, -0.8711, -0.5627,  0.2065,  0.2665,  0.4075, -1.1461,  1.2605,
          1.8970, -1.0819],
        [-0.1524, -1.7382,  0.5776, -0.7032,  1.1580, -0.6931,  0.5757, -0.9185,
         -0.2969, -2.1647]])


In [9]:
describe(torch.zeros(2, 3))
describe(torch.ones(2, 3))
a = torch.ones(2, 3)
a.fill_(5)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [18]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]]) # there's a difference between using .Tensor -> will make FloatTensor and .tensor!
print(b)
print(type(b))
print(type(torch.FloatTensor([[1, 2, 3], [4, 5, 6]]))) # apparently both are still of type TorchTensor

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
<class 'torch.Tensor'>


Values from PyTorch tensors can come from lists or NumPy arrays

In [32]:
c = torch.tensor(np.array([[1, 2, 3], [4,5, 6]]))
describe(c)

c = c.float()
describe(c)

c = c.long()
describe(c) # okay so even LongTensors are under Tensor now

d = torch.arange(6)
describe(d)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[1, 2, 3],
        [4, 5, 6]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[1, 2, 3],
        [4, 5, 6]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([6])
Values: tensor([0, 1, 2, 3, 4, 5])


In [42]:
x = torch.arange(6).view(2, 3)
describe(x)

describe(x[:1, :3]) # the first one captures the rows that will be included, second one are the columns

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([1, 3])
Values: tensor([[0, 1, 2]])


In [48]:
indices = torch.LongTensor([0, 2]) # there's a difference between using .Tensor and .tensor here apparently
describe(torch.index_select(x, dim = 1, index = indices))

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
Values: tensor([[0, 2],
        [3, 5]])


In [52]:
display(torch.cat([x, x], dim = 0))
display(torch.cat([x, x], dim = 1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])

In [54]:
x1 = torch.arange(6).view(2, 3).float() # so arange doesn't return FloatTensors now, interesting
describe(x1)

x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

describe(torch.mm(x1, x2))

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[0., 1., 2.],
        [3., 4., 5.]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 2])
Values: tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
Values: tensor([[ 3.,  6.],
        [12., 24.]])


In [60]:
x = torch.ones(2, 3, requires_grad = True)
describe(x)
print("===")

y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

print("===")
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
===
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
Values: tensor([[21., 21., 21.],
        [21., 21., 21.]], grad_fn=<AddBackward0>)
True
===
Type: <class 'torch.Tensor'>
Shape: torch.Size([])
Values: 21.0
False


In [63]:
print(torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

x = torch.rand(3, 3).to(device)
describe(x)

False
cpu
Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 3])
Values: tensor([[0.4510, 0.0799, 0.4953],
        [0.3005, 0.5245, 0.6862],
        [0.2400, 0.6355, 0.0926]])
